modules/yats/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import  url, include
from yats.views import root, info, show_board, board_by_id, yatse_api, login, logout, kanban, xptest, robots, autocomplete
from yats.tickets import new, action, table, search, search_ex, search_simple, reports, workflow, simple, create, log
from yats.docs import docs_action, docs_new
from rpc4django.views import serve_rpc_request
from markdownx import urls as markdownx

handler500 = 'yats.errors.server_error'

urlpatterns = [
    url(r'^rpc/$',
        view=serve_rpc_request,
        name='tx.tickets.callback'),

   url(r'^$',
        view=root,
        name='view_root'),

   # tickets
   url(r'^tickets/create/$',
        view=create,
        name='create'),

   url(r'^tickets/new/$',
        view=new,
        name='new'),

   url(r'^tickets/simple/$',
        view=simple,
        name='simple'),

   url(r'^tickets/list/$',
        view=table,
        name='table'),

   url(r'^tickets/search/$',
        view=search,
        name='search'),

   url(r'^tickets/search/simple/$',
        view=search_simple,
        name='search_simple'),

   url(r'^tickets/search/extended/$',
        view=search_ex,
        name='search_ex'),

   url(r'^tickets/(?P<mode>\w+)/(?P<ticket>\d+)/$',
        view=action,
        name='action'),

   # search
   url(r'^search/', include('haystack.urls')),

   # search
   url(r'^search/auto/',
        view=autocomplete,
        name='autocomplete'),

   # reports
   url(r'^reports/$',
        view=reports,
        name='reports'),

   # workflow
   url(r'^workflow/$',
        view=workflow,
        name='workflow'),

   # boards
   url(r'^board/(?P<id>\d+)/$',
        view=board_by_id,
        name='board_by_id'),

   url(r'^board/(?P<name>[\w|\W]+)/$',
        view=show_board,
        name='board'),

   # kanban
   url(r'^kanban/$',
        view=kanban,
        name='kanban'),

   # info
   url(r'^info/$',
        view=info,
        name='info'),

   # local login
   url(r'^local_login/$',
        view=login,
        name='login'),

   url(r'^local_logout/$',
        view=logout,
        name='logout'),

   # docs
   url(r'^docs/(?P<mode>\w+)/(?P<docid>\d+)/$',
        view=docs_action,
        name='docs_action'),

   url(r'^docs/new/$',
        view=docs_new,
        name='docs_new'),

   # log
   url(r'^log/$',
        view=log,
        name='log'),

   # yatse
   url(r'^yatse/$',
        view=yatse_api,
        name='yatse_api'),

   # xptest
   url(r'^xptest/(?P<test>[\w|\W]+)/$',
        view=xptest,
        name='xptest'),

   # robots
   url(r'^robots\.txt',
        view=robots,
        name='robots'),

    url(r'^markdownx/', include(markdownx)),
]

modules/yats/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.conf import settings
from django.forms.models import construct_instance
from bootstrap_toolkit.widgets import BootstrapDateTimeInput, BootstrapDateInput
from django.utils.translation import ugettext as _
from yats.fields import yatsFileField
from yats.models import ticket_resolution, ticket_flow, ticket_flow_edges, boards, ticket_priority, docs
from web.models import ticket_component

import importlib

mod_path, cls_name = settings.TICKET_CLASS.rsplit('.', 1)
mod = importlib.import_module(mod_path)
mod_cls = getattr(mod, cls_name)

def save_instance(form, instance, fields=None, fail_message='saved',
                  commit=True, exclude=None, construct=True, user=None):
    """
    Saves bound Form ``form``'s cleaned_data into model instance ``instance``.

    If commit=True, then the changes to ``instance`` will be saved to the
    database. Returns ``instance``.

    If construct=False, assume ``instance`` has already been constructed and
    just needs to be saved.
    """
    if construct:
        instance = construct_instance(form, instance, fields, exclude)
    opts = instance._meta
    if form.errors:
        raise ValueError("The %s could not be %s because the data didn't"
                         " validate." % (opts.object_name, fail_message))

    # Wrap up the saving of m2m data as a function.
    def save_m2m():
        cleaned_data = form.cleaned_data
        # Note that for historical reasons we want to include also
        # virtual_fields here. (GenericRelation was previously a fake
        # m2m field).

        for f in list(opts.many_to_many) + opts.virtual_fields:
            if not hasattr(f, 'save_form_data'):
                continue
            if fields and f.name not in fields:
                continue
            if exclude and f.name in exclude:
                continue
            if f.name in cleaned_data:
                f.save_form_data(instance, cleaned_data[f.name])
    if commit:
        # If we are committing, save the instance and the m2m data immediately.
        instance.save(user=user)
        save_m2m()
    else:
        # We're not committing. Add a method to the form to allow deferred
        # saving of m2m data.
        form.save_m2m = save_m2m
    return instance

class TicketsForm(forms.ModelForm):
    required_css_class = 'required'

    file_addition = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        if not 'user' in kwargs:
            raise Exception('missing user')
        self.user = kwargs.pop('user')
        self.view_only = kwargs.pop('view_only', False)

        if not 'customer' in kwargs:
            raise Exception('missing customer')
        self.customer = kwargs.pop('customer')

        if 'exclude_list' in kwargs:
            exclude_list = kwargs.pop('exclude_list')
        else:
            exclude_list = []

        if not 'is_stuff' in kwargs or not kwargs.pop('is_stuff'):
            exclude_list = list(set(exclude_list + settings.TICKET_NON_PUBLIC_FIELDS))

            super(TicketsForm, self).__init__(*args, **kwargs)

            if self.fields.get('customer'):
                self.fields['customer'].queryset = self.fields['customer'].queryset.filter(pk=self.customer)
        else:
            super(TicketsForm, self).__init__(*args, **kwargs)

        for field in exclude_list:
            del self.fields[field]

        for field in self.fields:
            if type(self.fields[field]) is forms.fields.DateField:
                self.fields[field].widget = BootstrapDateInput()

            if type(self.fields[field]) is forms.fields.DateTimeField:
                self.fields[field].widget = BootstrapDateTimeInput()

        # remove fields after close
        if not self.instance.pk is None and self.instance.closed and not self.view_only:
            available_fields = []
            for field in self.fields:
                available_fields.append(str(field))

            for field in available_fields:
                if str(field) not in settings.TICKET_EDITABLE_FIELDS_AFTER_CLOSE:
                    del self.fields[str(field)]

        # disallow non state
        if 'state' in self.fields:
            self.fields['state'].empty_label = None

            # only allow possible states
            if not self.instance.pk is None and not self.view_only:
                flows = list(ticket_flow_edges.objects.select_related('next').filter(now=self.instance.state).exclude(next__type=2).values_list('next', flat=True))
                flows.append(self.instance.state_id)
                self.fields['state'].queryset = self.fields['state'].queryset.filter(id__in=flows)

    def save(self, commit=True):
        """
        Saves this ``form``'s cleaned_data into model instance
        ``self.instance``.

        If commit=True, then the changes to ``instance`` will be saved to the
        database. Returns ``instance``.
        """
        if self.instance.pk is None:
            fail_message = 'created'
        else:
            fail_message = 'changed'
        return save_instance(self, self.instance, self._meta.fields,
                             fail_message, commit, self._meta.exclude,
                             construct=False, user=self.user)

    def clean_description(self):
        description = self.cleaned_data['description']
        return description.replace(u"\u00A0", " ")

    class Meta:
        model = mod_cls
        exclude = ['c_date', 'c_user', 'u_date', 'u_user', 'd_date', 'd_user', 'active_record', 'closed', 'close_date', 'last_action_date', 'keep_it_simple', 'uuid', 'hasAttachments', 'hasComments']


def get_simple_priority():
    if hasattr(settings, 'KEEP_IT_SIMPLE') and settings.KEEP_IT_SIMPLE and hasattr(settings, 'KEEP_IT_SIMPLE_DEFAULT_PRIORITY') and settings.KEEP_IT_SIMPLE_DEFAULT_PRIORITY:
        return settings.KEEP_IT_SIMPLE_DEFAULT_PRIORITY
    else:
        return None
class ToDo(forms.Form):
    text = forms.CharField(required=True)
    item = forms.IntegerField(required=True)
    set = forms.BooleanField(required=False)

class SimpleTickets(forms.Form):
    caption = forms.CharField(required=True, label=_('caption'))
    description = forms.CharField(widget=forms.Textarea(), required=False, label=_('description'))
    assigned = forms.ModelChoiceField(queryset=User.objects.all(), required=False, label=_('assigned'))
    priority = forms.ModelChoiceField(queryset=ticket_priority.objects.all(), required=False, initial=get_simple_priority, label=_('priority'), empty_label=None)
    deadline = forms.DateTimeField(widget=BootstrapDateTimeInput(format='dd.mm.yyyy hh:ii'), required=False, label=_('deadline'))
    component = forms.ModelChoiceField(queryset=ticket_component.objects.all(), required=False, label=_('component'))


class SearchForm(forms.ModelForm):
    required_css_class = 'do_not_require'

    def __init__(self, *args, **kwargs):
        if not 'user' in kwargs:
            raise Exception('missing user')
        self.user = kwargs.pop('user')

        if not 'customer' in kwargs:
            raise Exception('missing customer')
        self.customer = kwargs.pop('customer')

        if 'include_list' in kwargs:
            include_list = kwargs.pop('include_list')
        else:
            include_list = []

        if not 'is_stuff' in kwargs or not kwargs.pop('is_stuff'):
            used_fields = []
            for ele in include_list:
                if not ele in settings.TICKET_NON_PUBLIC_FIELDS:
                    used_fields.append(ele)
            super(SearchForm, self).__init__(*args, **kwargs)

            if self.fields.get('customer'):
                self.fields['customer'].queryset = self.fields['customer'].queryset.filter(pk=self.customer)
        else:
            used_fields = include_list
            super(SearchForm, self).__init__(*args, **kwargs)
        available_fields = []
        for field in self.fields:
            available_fields.append(str(field))

        for field in available_fields:
            if str(field) not in used_fields:
                del self.fields[str(field)]

        for field in self.fields:
            if type(self.fields[field]) is forms.fields.DateField:
                self.fields[field].widget = BootstrapDateInput()

            if type(self.fields[field]) is forms.fields.DateTimeField:
                self.fields[field].widget = BootstrapDateTimeInput()

            if type(self.fields[field]) is forms.fields.BooleanField:
                self.fields[field] = forms.NullBooleanField()

            self.fields[field].required = False

        """
        # add fulltext
        field = forms.CharField(required=False, label=_('full text search'))
        setattr(self, 'fulltext', field)
        self.fields['fulltext'] = field

        self.field_order = ['fulltext']
        for field in self.fields:
            self.field_order.append(field)
        self.field_order.pop()
        """

        # unset initial
        for field in self.fields:
            self.fields[field].initial = None

    def save(self, commit=True):
        """
        Saves this ``form``'s cleaned_data into model instance
        ``self.instance``.

        If commit=True, then the changes to ``instance`` will be saved to the
        database. Returns ``instance``.
        """
        if self.instance.pk is None:
            fail_message = 'created'
        else:
            fail_message = 'changed'
        return save_instance(self, self.instance, self._meta.fields,
                             fail_message, commit, self._meta.exclude,
                             construct=False, user=self.user)

    class Meta:
        model = mod_cls
        exclude = []
        labels = {
            'c_date': _('created'),
            'u_date': _('updated'),
            'd_date': _('deleted'),
            'c_user': _('created by'),

modules/yats/templates/board/kanban.html
{% extends "base.html" %}

{% load bootstrap_toolkit i18n boards %}

{% block title %}{% trans "kanban" %}{% endblock %}

{% block extra_head %}
<script src="{{ STATIC_URL }}board.js"></script>
<link rel="stylesheet" href="{{ STATIC_URL }}board.css">
<style>
  .new { background-color: #51a351; }
  .done { background-color: #bd362f; }
  .flow {
    border: 1px solid #428bca;
    border-color: #428bca;
    background-color: white;
    color: black;
  }
</style>
{% endblock %}

{% block content %}

    <h2>{% trans "getting things done" %}</h2>

    <p>{% trans "Drag and drop tickets from one state to the next one accoring to the workflow. Use CTRL or ALT for moving only (no reassign)" %}</p>

    <div class="container-fluid">
        <div class="row">
          <div id="alert_placeholder"></div>
        </div>
        <div id="sortableKanbanBoards" class="row">

            {% for column in columns %}<div class="panel panel-primary kanban-col">
                <div class="panel-heading {% if column.type == 0 %}flow{% endif %}{% if column.type == 1 %}new{% endif %}{% if column.type == 2 %}done{% endif %}">
                    {{ column.name }}
                </div>
                <div class="panel-body">
                    <div id="list{{ column.id }}" class="kanban-centered">
                        {% for ticket in column.data %}{% lookup_seen column.seen ticket %}{% if seen != 2 %}<article class="kanban-entry grab" id="item{{ ticket.pk }}" draggable="true">
                            <div class="kanban-entry-inner">
                                <div class="kanban-label"{% if ticket.priority.color %} style="background-color:{{ ticket.priority.color }};"{% endif %}>
                                    <h2><a href="/tickets/view/{{ ticket.pk }}/">#{{ ticket.pk }}</a> {{ ticket.caption }}</h2>
                                    {% if ticket.deadline and not ticket.closed %}<small class="text-muted"{% if ticket.is_late == 2 %} style="color: red;"{% endif %}{% if ticket.is_late == 1 %} style="color: orange;"{% endif %}><i class="icon-time"></i> {{ ticket.deadline }}</small>{% endif %}
                                    {% if ticket.hasAttachments %}<i class="icon-file"></i>{% endif %}{% if ticket.hasComments %}<i class="fa fa-comments" aria-hidden="true"></i>{% endif %}{% if ticket.assigned %}<small class="text-muted"><i class="icon-user"></i> {{ ticket.assigned }}</small>{% endif %}
                                    {% if request.user.is_staff and ticket.customer and ticket.billing_estimated_time and ticket.customer.hourly_rate %}<small class="text-muted"><b>€</b> {{ ticket.customer.hourly_rate|multiply:ticket.billing_estimated_time|floatformat:"0" }}</small>{% endif %}
                                    {% if seen == 1 %}<a href="javascript: seen({{ ticket.pk }});"><i class="icon-eye-open pull-right"></i></a>{% else %}<a href="javascript: ignore({{ ticket.pk }});"><i class="icon-eye-open pull-right"></i></a>{% endif %}
                                </div>
                            </div>
                        </article>
                        {% endif %}{% endfor %}

                    </div>
                </div>
            </div>{% endfor %}

        </div>
    </div>


    <!-- Static Modal -->
    <div class="modal modal-static fade" id="processing-modal" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="text-center">
                        <i class="fa fa-refresh fa-5x fa-spin"></i>
                        <h4>Processing...</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="closeDlg" class="modal hide fade">

        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>{% trans "close ticket" %}</h3>
        </div>

        <form class="form-{{ layout }}" action="" method="post">
        <div class="modal-body">
	        {% csrf_token %}
	        {{ close|as_bootstrap:layout }}
        </div>

        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">{% trans "cancel" %}</a>
            <a href="javascript: close();" class="btn btn-danger">{% trans "close" %}</a>
        </div>
        </form>
    </div>

    <div id="reassignDlg" class="modal hide fade">

        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>{% trans "reassign ticket" %}</h3>
        </div>

        <form class="form-{{ layout }}" action="/tickets/reassign/0/" method="post">
        <div class="modal-body">
            {% csrf_token %}
            {{ reassign|as_bootstrap:layout }}
        </div>

        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">{% trans "cancel" %}</a>
            <a href="javascript: reassign();" class="btn btn-warning">{% trans "reassign" %}</a>
        </div>
        </form>
    </div>


    <script>
    var finish_state = {{ finish_state }};
    var ticketid;
    var list_items;
    var all_states;

    var edges = {
      {% for edge in edges %}{% ifchanged edge.now %}{% if not forloop.first %}],
      {% endif %}"{{ edge.now.id }}": [{% else %},{% endifchanged %}{{ edge.next.id }}{% if forloop.last %}]{% endif %}{% endfor %}
    }

    function close() {
      form = $('#closeDlg').find('form');

      if ( ! $('#id_resolution').val() || ! $('#id_close_comment').val() ) {
        alert('{% trans "Please fill out the required fields!" %}');
        return;
      }

      $.post('/tickets/view/' + ticketid + '/', form.serialize(),  function(data) {
          var element = document.getElementById('item' + ticketid);
          list_items.prepend(element);
          $('#closeDlg').modal('toggle');
        }
      );
    }

    function reassign() {
      form = $('#reassignDlg').find('form');

      if ( ! $('#id_assigned').val() || ! $('#id_reassign_comment').val() ) {
        alert('{% trans "Please fill out the required fields!" %}');
        return;
      }

      $.post('/tickets/reassign/' + ticketid + '/', form.serialize(),  function(data) {
          var element = document.getElementById('item' + ticketid);
          list_items.prepend(element);
          $('#reassignDlg').modal('toggle');
        }
      );
    }

    function move(ticketid, state) {
      $.post('/tickets/move/' + ticketid + '/', 'simple=1&state=' + state,  function(data) {
        var element = document.getElementById('item' + ticketid);
        list_items.prepend(element);

        $('#processing-modal').modal('toggle');
        }
      );
    }

    function seen(ticket) {
      if (confirm('{% trans "Do you really want to remove this ticket from this board until the next change of that ticket?" %}') ) {
        $.get("/tickets/notify/" + ticket + "/", function(data, status) {
            $('#item' + ticket).remove();
        });
      }
    }

    function ignore(ticket) {
      if (confirm('{% trans "Do you really want to remove this ticket from this board until the next change of that ticket?" %}') ) {
        $.get("/tickets/ignore/" + ticket + "/", function(data, status) {
            $('#item' + ticket).remove();
        });
      }
    }
    </script>
{% endblock %}

{% block footer %}
<div class="container-fluid">
  <hr />

  <div class="row-fluid">

    <div class="span6">
      {{ SETTINGS.CUSTOMER }}<br />
      {{ SETTINGS.TEL }}<br />
      {{ SETTINGS.MAIL }}<br />
    </div>
      <div class="span6">
          <p class="text-right">
              &copy; 2014 - {% now "Y" %} <a href="http://www.mediafactory.de">media factory</a>
          </p>
      </div>
  </div>
</div>
{% endblock %}

modules/yats/templates/board/view.html
{% extends "base.html" %}

{% load bootstrap_toolkit i18n boards %}

{% block title %}{{ board.name }} {% trans "board" %}{% endblock %}

{% block extra_head %}
<script src="{{ STATIC_URL }}board.js"></script>
<link rel="stylesheet" href="{{ STATIC_URL }}board.css">
{% endblock %}

{% block content %}

    <h2><a href="javascript: delBoard();"><i class="fa fa-trash-o"></i></a> {{ board.name }} {% trans "board" %}</h2>

    <p>{% trans "add new columns by adding a search result to this board" %}</p>

    <div class="container-fluid">
        <div id="sortableKanbanBoards" class="row">

            {% for column in columns %}<div class="panel panel-primary kanban-col">
                <div class="panel-heading">
                    <a href="javascript: delColumn('{{ column.column }}')"><i class="icon-trash icon-white"></i></a>&nbsp;&nbsp;{{ column.column }}
                </div>
                <div class="panel-body">
                    <div id="{{ column.column }}" class="kanban-centered">
                        {% for ticket in column.query %}{% lookup_seen column.seen ticket %}{% if seen != 2 %}<article class="kanban-entry grab" id="item{{ ticket.pk }}">
                            <div class="kanban-entry-inner">
                                <div class="kanban-label"{% if ticket.priority.color %} style="background-color:{{ ticket.priority.color }};"{% endif %}>
                                    <h2><a href="/tickets/view/{{ ticket.pk }}/">#{{ ticket.pk }}</a> {{ ticket.caption }}</h2>
                                    {% if ticket.deadline and not ticket.closed %}<small class="text-muted"{% if ticket.is_late == 2 %} style="color: red;"{% endif %}{% if ticket.is_late == 1 %} style="color: orange;"{% endif %}><i class="icon-time"></i> {{ ticket.deadline }}</small>{% endif %}
                                    {% if ticket.hasAttachments %}<i class="icon-file"></i>{% endif %}{% if ticket.hasComments %}<i class="fa fa-comments" aria-hidden="true"></i>{% endif %}{% if ticket.assigned %}<small class="text-muted"><i class="icon-user"></i> {{ ticket.assigned }}</small>{% endif %}
                                    {% if request.user.is_staff and ticket.customer and ticket.billing_estimated_time and ticket.customer.hourly_rate %}<small class="text-muted"><b>€</b> {{ ticket.customer.hourly_rate|multiply:ticket.billing_estimated_time|floatformat:"0" }}</small>{% endif %}
                                    {% if seen == 1 %}<a href="javascript: seen({{ ticket.pk }});"><i class="icon-eye-open pull-right"></i></a>{% else %}<a href="javascript: ignore({{ ticket.pk }});"><i class="icon-eye-open pull-right"></i></a>{% endif %}
                                </div>
                            </div>
                        </article>
                        {% endif %}{% endfor %}

                    </div>
                </div>
            </div>{% endfor %}

        </div>
    </div>


    <!-- Static Modal -->
    <div class="modal modal-static fade" id="processing-modal" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="text-center">
                        <i class="fa fa-refresh fa-5x fa-spin"></i>
                        <h4>Processing...</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
    	function delColumn(col) {
    		if (confirm('{% trans "Do you really want to delete this column?" %}') )
                window.location.href = '/board/{{ board.name }}/?method=del&column=' + encodeURIComponent(col);
    	}

      function delBoard() {
        if (confirm('{% trans "Do you really want to delete this board?" %}') )
                window.location.href = '/board/{{ board.name }}/?method=delete';
      }

      function seen(ticket) {
        if (confirm('{% trans "Do you really want to remove this ticket from this board until the next change of that ticket?" %}') ) {
          $.get("/tickets/notify/" + ticket + "/", function(data, status) {
              $('#item' + ticket).remove();
          });
        }
      }

      function ignore(ticket) {
        if (confirm('{% trans "Do you really want to remove this ticket from this board until the next change of that ticket?" %}') ) {
          $.get("/tickets/ignore/" + ticket + "/", function(data, status) {
              $('#item' + ticket).remove();
          });
        }
      }
    </script>
{% endblock %}

{% block footer %}
<div class="container-fluid">
  <hr />

  <div class="row-fluid">

    <div class="span6">
      {{ SETTINGS.CUSTOMER }}<br />
      {{ SETTINGS.TEL }}<br />
      {{ SETTINGS.MAIL }}<br />
    </div>
      <div class="span6">
          <p class="text-right">
              &copy; 2014 - {% now "Y" %} <a href="http://www.mediafactory.de">media factory</a>
          </p>
      </div>
  </div>
</div>
{% endblock %}