modules/yats/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import  url, include
from yats.views import root, info, show_board, board_by_id, yatse_api, login, logout, kanban, xptest, robots, autocomplete
from yats.tickets import new, action, table, search, search_ex, search_simple, reports, workflow, simple, create, log
from yats.docs import docs_action, docs_new
from rpc4django.views import serve_rpc_request
from markdownx import urls as markdownx

handler500 = 'yats.errors.server_error'

urlpatterns = [
    url(r'^rpc/$',
        view=serve_rpc_request,
        name='tx.tickets.callback'),

   url(r'^$',
        view=root,
        name='view_root'),

   # tickets
   url(r'^tickets/create/$',
        view=create,
        name='create'),

   url(r'^tickets/new/$',
        view=new,
        name='new'),

   url(r'^tickets/simple/$',
        view=simple,
        name='simple'),

   url(r'^tickets/list/$',
        view=table,
        name='table'),

   url(r'^tickets/search/$',
        view=search,
        name='search'),

   url(r'^tickets/search/simple/$',
        view=search_simple,
        name='search_simple'),

   url(r'^tickets/search/extended/$',
        view=search_ex,
        name='search_ex'),

   url(r'^tickets/(?P<mode>\w+)/(?P<ticket>\d+)/$',
        view=action,
        name='action'),

   # search
   url(r'^search/', include('haystack.urls')),

   # search
   url(r'^search/auto/',
        view=autocomplete,
        name='autocomplete'),

   # reports
   url(r'^reports/$',
        view=reports,
        name='reports'),

   # workflow
   url(r'^workflow/$',
        view=workflow,
        name='workflow'),

   # boards
   url(r'^board/(?P<id>\d+)/$',
        view=board_by_id,
        name='board_by_id'),

   url(r'^board/(?P<name>[\w|\W]+)/$',
        view=show_board,
        name='board'),

   # kanban
   url(r'^kanban/$',
        view=kanban,
        name='kanban'),

   # info
   url(r'^info/$',
        view=info,
        name='info'),

   # local login
   url(r'^local_login/$',
        view=login,
        name='login'),

   url(r'^local_logout/$',
        view=logout,
        name='logout'),

   # docs
   url(r'^docs/(?P<mode>\w+)/(?P<docid>\d+)/$',
        view=docs_action,
        name='docs_action'),

   url(r'^docs/new/$',
        view=docs_new,
        name='docs_new'),

   # log
   url(r'^log/$',
        view=log,
        name='log'),

   # yatse
   url(r'^yatse/$',
        view=yatse_api,
        name='yatse_api'),

   # xptest
   url(r'^xptest/(?P<test>[\w|\W]+)/$',
        view=xptest,
        name='xptest'),

   # robots
   url(r'^robots\.txt',
        view=robots,
        name='robots'),

    url(r'^markdownx/', include(markdownx)),
]

modules/yats/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.conf import settings
from django.forms.models import construct_instance
from bootstrap_toolkit.widgets import BootstrapDateTimeInput, BootstrapDateInput
from django.utils.translation import ugettext as _
from yats.fields import yatsFileField
from yats.models import ticket_resolution, ticket_flow, ticket_flow_edges, boards, ticket_priority, docs
from web.models import ticket_component

import importlib

mod_path, cls_name = settings.TICKET_CLASS.rsplit('.', 1)
mod = importlib.import_module(mod_path)
mod_cls = getattr(mod, cls_name)

def save_instance(form, instance, fields=None, fail_message='saved',
                  commit=True, exclude=None, construct=True, user=None):
    """
    Saves bound Form ``form``'s cleaned_data into model instance ``instance``.

    If commit=True, then the changes to ``instance`` will be saved to the
    database. Returns ``instance``.

    If construct=False, assume ``instance`` has already been constructed and
    just needs to be saved.
    """
    if construct:
        instance = construct_instance(form, instance, fields, exclude)
    opts = instance._meta
    if form.errors:
        raise ValueError("The %s could not be %s because the data didn't"
                         " validate." % (opts.object_name, fail_message))

    # Wrap up the saving of m2m data as a function.
    def save_m2m():
        cleaned_data = form.cleaned_data
        # Note that for historical reasons we want to include also
        # virtual_fields here. (GenericRelation was previously a fake
        # m2m field).

        for f in list(opts.many_to_many) + opts.virtual_fields:
            if not hasattr(f, 'save_form_data'):
                continue
            if fields and f.name not in fields:
                continue
            if exclude and f.name in exclude:
                continue
            if f.name in cleaned_data:
                f.save_form_data(instance, cleaned_data[f.name])
    if commit:
        # If we are committing, save the instance and the m2m data immediately.
        instance.save(user=user)
        save_m2m()
    else:
        # We're not committing. Add a method to the form to allow deferred
        # saving of m2m data.
        form.save_m2m = save_m2m
    return instance

class TicketsForm(forms.ModelForm):
    required_css_class = 'required'

    file_addition = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        if not 'user' in kwargs:
            raise Exception('missing user')
        self.user = kwargs.pop('user')
        self.view_only = kwargs.pop('view_only', False)

        if not 'customer' in kwargs:
            raise Exception('missing customer')
        self.customer = kwargs.pop('customer')

        if 'exclude_list' in kwargs:
            exclude_list = kwargs.pop('exclude_list')
        else:
            exclude_list = []

        if not 'is_stuff' in kwargs or not kwargs.pop('is_stuff'):
            exclude_list = list(set(exclude_list + settings.TICKET_NON_PUBLIC_FIELDS))

            super(TicketsForm, self).__init__(*args, **kwargs)

            if self.fields.get('customer'):
                self.fields['customer'].queryset = self.fields['customer'].queryset.filter(pk=self.customer)
        else:
            super(TicketsForm, self).__init__(*args, **kwargs)

        for field in exclude_list:
            del self.fields[field]

        for field in self.fields:
            if type(self.fields[field]) is forms.fields.DateField:
                self.fields[field].widget = BootstrapDateInput()

            if type(self.fields[field]) is forms.fields.DateTimeField:
                self.fields[field].widget = BootstrapDateTimeInput()

        # remove fields after close
        if not self.instance.pk is None and self.instance.closed and not self.view_only:
            available_fields = []
            for field in self.fields:
                available_fields.append(str(field))

            for field in available_fields:
                if str(field) not in settings.TICKET_EDITABLE_FIELDS_AFTER_CLOSE:
                    del self.fields[str(field)]

        # disallow non state
        if 'state' in self.fields:
            self.fields['state'].empty_label = None

            # only allow possible states
            if not self.instance.pk is None and not self.view_only:
                flows = list(ticket_flow_edges.objects.select_related('next').filter(now=self.instance.state).exclude(next__type=2).values_list('next', flat=True))
                flows.append(self.instance.state_id)
                self.fields['state'].queryset = self.fields['state'].queryset.filter(id__in=flows)

    def save(self, commit=True):
        """
        Saves this ``form``'s cleaned_data into model instance
        ``self.instance``.

        If commit=True, then the changes to ``instance`` will be saved to the
        database. Returns ``instance``.
        """
        if self.instance.pk is None:
            fail_message = 'created'
        else:
            fail_message = 'changed'
        return save_instance(self, self.instance, self._meta.fields,
                             fail_message, commit, self._meta.exclude,
                             construct=False, user=self.user)

    def clean_description(self):
        description = self.cleaned_data['description']
        return description.replace(u"\u00A0", " ")

    class Meta:
        model = mod_cls
        exclude = ['c_date', 'c_user', 'u_date', 'u_user', 'd_date', 'd_user', 'active_record', 'closed', 'close_date', 'last_action_date', 'keep_it_simple', 'uuid', 'hasAttachments', 'hasComments']


def get_simple_priority():
    if hasattr(settings, 'KEEP_IT_SIMPLE') and settings.KEEP_IT_SIMPLE and hasattr(settings, 'KEEP_IT_SIMPLE_DEFAULT_PRIORITY') and settings.KEEP_IT_SIMPLE_DEFAULT_PRIORITY:
        return settings.KEEP_IT_SIMPLE_DEFAULT_PRIORITY
    else:
        return None
class ToDo(forms.Form):
    text = forms.CharField(required=True)
    item = forms.IntegerField(required=True)
    set = forms.BooleanField(required=False)

class SimpleTickets(forms.Form):
    caption = forms.CharField(required=True, label=_('caption'))
    description = forms.CharField(widget=forms.Textarea(), required=False, label=_('description'))
    assigned = forms.ModelChoiceField(queryset=User.objects.all(), required=False, label=_('assigned'))
    priority = forms.ModelChoiceField(queryset=ticket_priority.objects.all(), required=False, initial=get_simple_priority, label=_('priority'), empty_label=None)
    deadline = forms.DateTimeField(widget=BootstrapDateTimeInput(format='dd.mm.yyyy hh:ii'), required=False, label=_('deadline'))
    component = forms.ModelChoiceField(queryset=ticket_component.objects.all(), required=False, label=_('component'))


class SearchForm(forms.ModelForm):
    required_css_class = 'do_not_require'

    def __init__(self, *args, **kwargs):
        if not 'user' in kwargs:
            raise Exception('missing user')
        self.user = kwargs.pop('user')

        if not 'customer' in kwargs:
            raise Exception('missing customer')
        self.customer = kwargs.pop('customer')

        if 'include_list' in kwargs:
            include_list = kwargs.pop('include_list')
        else:
            include_list = []

        if not 'is_stuff' in kwargs or not kwargs.pop('is_stuff'):
            used_fields = []
            for ele in include_list:
                if not ele in settings.TICKET_NON_PUBLIC_FIELDS:
                    used_fields.append(ele)
            super(SearchForm, self).__init__(*args, **kwargs)

            if self.fields.get('customer'):
                self.fields['customer'].queryset = self.fields['customer'].queryset.filter(pk=self.customer)
        else:
            used_fields = include_list
            super(SearchForm, self).__init__(*args, **kwargs)
        available_fields = []
        for field in self.fields:
            available_fields.append(str(field))

        for field in available_fields:
            if str(field) not in used_fields:
                del self.fields[str(field)]

        for field in self.fields:
            if type(self.fields[field]) is forms.fields.DateField:
                self.fields[field].widget = BootstrapDateInput()

            if type(self.fields[field]) is forms.fields.DateTimeField:
                self.fields[field].widget = BootstrapDateTimeInput()

            if type(self.fields[field]) is forms.fields.BooleanField:
                self.fields[field] = forms.NullBooleanField()

            self.fields[field].required = False

        """
        # add fulltext
        field = forms.CharField(required=False, label=_('full text search'))
        setattr(self, 'fulltext', field)
        self.fields['fulltext'] = field

        self.field_order = ['fulltext']
        for field in self.fields:
            self.field_order.append(field)
        self.field_order.pop()
        """

        # unset initial
        for field in self.fields:
            self.fields[field].initial = None

    def save(self, commit=True):
        """
        Saves this ``form``'s cleaned_data into model instance
        ``self.instance``.

        If commit=True, then the changes to ``instance`` will be saved to the
        database. Returns ``instance``.
        """
        if self.instance.pk is None:
            fail_message = 'created'
        else:
            fail_message = 'changed'
        return save_instance(self, self.instance, self._meta.fields,
                             fail_message, commit, self._meta.exclude,
                             construct=False, user=self.user)

    class Meta:
        model = mod_cls
        exclude = []
        labels = {
            'c_date': _('created'),
            'u_date': _('updated'),
            'd_date': _('deleted'),
            'c_user': _('created by'),

modules/yats/templates/tickets/debug.html
{{ query }}<br />

<br />
<br />

{% for q in queries %}
{{ q }}<br /><br />
{% endfor %}

modules/yats/templates/tickets/edit.html
{% extends "base.html" %}

{% load bootstrap_toolkit i18n %}

{% block title %}{% trans "edit ticket" %} #{{ ticket.id }}{% endblock %}

{% block extra_head %}
    {{ form.media }}
{% endblock %}

{% block content %}

    <h2>{% trans "edit ticket" %} #{{ ticket.id }}</h2>
    {% if mode == "simple" %}<p style="margin-top: -15px;"><small class="text-muted"><a href="/tickets/edit/{{ ticket.id }}/">{% trans "switch to extended form" %}</a></small></p>{% endif %}
    <p><small class="text-muted">{% trans "created" %}: {{ ticket.c_date }} by {{ ticket.c_user }}<br /> {% trans "last modified" %}: {{ ticket.u_date }} by {{ ticket.u_user }}</small></p>

    <p>&nbsp;</p>

    <form class="form-{{ layout }}" action="" method="post">
        {% csrf_token %}
        {{ form|as_bootstrap:layout }}
        {% if layout == "horizontal" %}
            <p class="form-actions">
                <input type="submit" value="{% trans "save" %}" class="btn btn-primary">
            </p>
        {% else %}
            <input type="submit" value="{% trans "save" %}" class="btn btn-primary">
        {% endif %}
    </form>

{% endblock %}

modules/yats/templates/tickets/file.html
{% extends "base.html" %}

{% load bootstrap_toolkit i18n strings %}

{% block title %}{% trans "file upload ticket" %} #{{ ticket.id }}{% endblock %}

{% block content %}
    <h2>{% trans "ticket" %} #{{ ticketid }}</h2>

    <p>&nbsp;</p>

	<form id="data" name="data" action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|as_bootstrap:"vertical" }}
	<br />
	<input class="btn btn-primary" type="submit" value="{% trans "upload" %}" />
	</form>

{% endblock %}

modules/yats/templates/tickets/gallery.html
{% extends "base.html" %}

{% load bootstrap_toolkit i18n strings %}

{% block title %}{% trans "file gallery ticket" %} #{{ ticket.id }}{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" href="{{ STATIC_URL }}/galereya/css/jquery.galereya.css">
    <!--[if lt IE 9]>
    <link rel="stylesheet" href="{{ STATIC_URL }}/galereya/css/jquery.galereya.ie.css">
    <![endif]-->
    <script src="{{ STATIC_URL }}/galereya/js/jquery.galereya.js"></script>
{% endblock %}

{% block content %}
    <h2>{% trans "ticket" %} #{{ ticket.id }} <button type="button" class="btn {% if ticket.closed %}btn-danger{% else %}btn-success{% endif %}" disabled>{% if ticket.closed %}{% trans "closed" %}: {{ ticket.resolution }}{% else %}{% trans "open" %}{% endif %}</button>&nbsp;&nbsp;<a class="btn btn-small" href="/tickets/view/{{ ticket.id }}/">{% trans "view" %}</a></h2>

    <p>&nbsp;</p>

    <div id="gallery">
      {% for image in images %}{% if image.content_type|hasPreview %}<img src="{% if "image" in image.content_type %}/tickets/download/{{ ticket.id }}/?file={{ image.id }}{% else %}/tickets/download/{{ ticket.id }}/?file={{ image.id }}&preview=yes{% endif %}"
          alt="{{ image.name }}"
          title="{{ image.name }}"
          data-desc="{{ image.content_tye }}"
          data-category="{{ image.content_tye }}"
          data-fullsrc="/tickets/download/{{ ticket.id }}/?file={{ image.id }}"
      />{% endif %}{% endfor %}
    </div>

    <script>
      $(function() {
          $('#gallery').galereya({
            wave: false,
            modifier: '',
            spacing: 5,
            disableSliderOnClick: true,
            onCellClick: function(e, ele) {
              //console.log(ele.childNodes[0].getAttribute('data-fullsrc'));
              window.location.href = ele.childNodes[0].getAttribute('data-fullsrc');
            }
        });
        $('footer').hide();
      });

    </script>

{% endblock %}

modules/yats/templates/tickets/history.html
{% extends "base.html" %}

{% load bootstrap_toolkit i18n forms strings comments %}

{% block title %}{% trans "ticket" %} #{{ ticket.id }}{% endblock %}

{% block extra_head %}
    {{ form.media }}
    <link href="{{ STATIC_URL }}timeline.css" type="text/css" rel="stylesheet" media="all">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css" />
    <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
{% endblock %}

{% block content %}

    <h2>{% trans "ticket" %} #{{ ticket.id }} <button type="button" class="btn {% if ticket.closed %}btn-danger{% else %}btn-success{% endif %}" disabled>{% if ticket.closed %}{% trans "closed" %}: {{ ticket.resolution }}{% else %}{% trans "open" %}{% endif %}</button>&nbsp;&nbsp;<a class="btn btn-small" href="/tickets/view/{{ ticket.id }}/">{% trans "view" %}</a>&nbsp;{% if not ticket.closed %}<a class="btn btn-small" href="/tickets/{% if keep_it_simple %}simple{% else %}edit{% endif %}/{{ ticket.id }}/">{% trans "edit" %}</a>{% endif %}</h2>
    <p><small class="text-muted">{% trans "created" %}: {{ ticket.c_date }} by {{ ticket.c_user }}<br /> {% trans "last modified" %}: {{ ticket.u_date }} by {{ ticket.u_user }}</small></p>
    <p>&nbsp;</p>

    <h3>{% trans "history" %}</h3>
    <hr />
    <ul class="timeline">
        {% for line in history %}
        {% diff line %}
        {% if elements %}
        <li{% cycle '' ' class="timeline-inverted"' %}>
          <div class="timeline-badge {{ line.action|comment_color }}"><i class="fa {{ line.action|history_icon }}"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <p><i class="icon-user"></i> <small class="text-muted">{{ line.c_user }} <i class="icon-time"></i> {{ line.c_date }}</small></p>
            </div>
            <div class="timeline-body">
              <p>
              	<table>
                {% for key, value in elements.items  %}
                <tr>
                	<td valign="top">{{ key|prettify }}:</td>
                    <td>{{ value|safe }}</td>
                </tr>
                {% endfor %}
                </table>
              </p>
            </div>
          </div>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
{% endblock %}

modules/yats/templates/tickets/list.html
{% extends "base.html" %}

{% load bootstrap_toolkit i18n strings tz %}

{% block title %}{% trans "ticket list" %}{% endblock %}

{% block content %}

    <h2>{% if is_search %}{% trans "search results for tickets" %}&nbsp;<a class="btn btn-small" href="/tickets/search/?new=1">{% trans "new search" %}</a>&nbsp;<a role="button" data-toggle="modal" class="btn btn-small" href="#saveDlg">{% trans "save search" %}</a>{% if boards|length > 0 %}&nbsp;<a role="button" data-toggle="modal" class="btn btn-small" href="#saveToBoardDlg">{% trans "save to board" %}</a>{% endif %}{% else %}{% trans "tickets" %}{% endif %}</h2>
    {% if list_caption %}<p><small class="text-muted">{% trans "report" %}: {{ list_caption }}</small></p>{% endif %}
    <p>&nbsp;</p>

    {% if lines %}
    <p>{{ lines.start_index }} - {{ lines.end_index }} {% trans "of" %} {{ lines.paginator.count }}</p>
    <section id="no-more-tables">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>{% trans "state" %}</th>
                <th></th>
                <th>{% trans "ticket#" %}</th>
                <th>{% trans "created" %}</th>
                <th>{% trans "type" %}</th>
                <th>{% trans "state" %}</th>
                <th>{% trans "assigned" %}</th>
                <th>{% trans "caption" %}</th>
            </tr>
            </thead>
              {% for line in lines %}
                <tr style="{% if line.priority.color != "transparent" %}background-color: {{ line.priority.color }}{% endif %}">
                	<td data-title="{% trans "state" %}"><button type="button" class="btn {% if line.closed %}btn-danger{% else %}btn-success{% endif %}" disabled /></td>
                    <td>{% if line.deadline %}<i class="icon-time"></i>{% endif %}{% if line.hasAttachments %}<i class="icon-file"></i>{% endif %}{% if line.hasComments %}<i class="fa fa-comments" aria-hidden="true"></i>{% endif %}</td>
                    <td data-title="{% trans "ticket#" %}"><a href="/tickets/view/{{ line.id }}/">#{{ line.id }}</a></td>
                    <td data-title="{% trans "created" %}">{{ line.c_date|localtime|date:"d.m.y H:i" }}</td>
                    <td data-title="{% trans "type" %}">{{ line.type|default:"&nbsp;" }}</td>
                    <td data-title="{% trans "state" %}">{{ line.state }}</td>
                    <td data-title="{% trans "assigned" %}">{{ line.assigned|default:"&nbsp;" }}</td>
                    <td data-title="{% trans "caption" %}">{{ line.caption }}</td>
                </tr>
            {% endfor %}
        </table>

        {{ lines|pagination }}
    </section>
    {% endif %}
    {% if lines.paginator.count == 0 %}
    {% trans "no tickets found!" %}
    {% endif %}
    <p><small class="text-muted">{% trans "You searched for:" %} {{ pretty_query }}</small></p>

    {% if is_search %}
    <div id="saveDlg" class="modal hide fade">

        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>{% trans "save as report" %}</h3>
        </div>

        <form class="form-{{ layout }}" action="/tickets/search/" method="post">
        <div class="modal-body">
				<div class="control-group">
					<label class="control-label" for="id_deadline">{% trans "report name" %}</label>
					<div class="controls">
						<div class="input-append reportname">
    						<input id="id_reportname" name="reportname" type="text" />
						</div>
					</div>
				</div>
		</div>

        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">{% trans "cancel" %}</a>
            <input type="submit" value="{% trans "save" %}" class="btn btn-primary">
        </div>
        </form>
    </div>

    <div id="saveToBoardDlg" class="modal hide fade">

        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>{% trans "save to board" %}</h3>
        </div>

        <form class="form-horizontal" action="/board/change_board/" method="post">
        <div class="modal-body">
            {{ board_form|as_bootstrap:"horizontal" }}
        </div>

        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">{% trans "cancel" %}</a>
            <input type="submit" value="{% trans "save" %}" class="btn btn-primary">
        </div>
        </form>
    </div>
    {% endif %}

{% if request.user.username == "henrik.genssen" %}{{ sql }}{% endif %}
{% endblock %}

modules/yats/templates/tickets/log.html
{% extends "base.html" %}

{% load bootstrap_toolkit i18n strings comments %}

{% block title %}{% trans "log" %}{% endblock %}

{% block content %}
    <h2>Logs</h2>

    <p>&nbsp;</p>

    {% if history %}
    <section id="no-more-tables">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>{% trans "date" %}</th>
                <th>{% trans "ticket" %}</th>
                <th>{% trans "action" %}</th>
                <th>{% trans "diff" %}</th>
            </tr>
            </thead>
              {% for line in history %}
                {% diff line %}
                <tr>
                    <td data-title="{% trans "date" %}">{{ line.c_date|date:"SHORT_DATETIME_FORMAT" }}</td>
                    <td data-title="{% trans "name" %}"><a href="/tickets/view/{{ line.ticket_id }}/">#{{ line.ticket_id }}</a></td>
                    <td data-title="{% trans "action" %}"><i class="fa {{ line.action|history_icon }}"></i></td>
                    <td data-title="{% trans "diff" %}">
                      <table>
                      {% for key, value in elements.items  %}
                      <tr>
                      	<td valign="top">{{ key|prettify }}:</td>
                          <td>{{ value|safe }}</td>
                      </tr>
                      {% endfor %}
                      </table>
                    </td>
                </tr>
            {% endfor %}
        </table>

        {{ history|pagination }}
    </section>
    {% else %}
    {% trans "no logs so far" %}
    {% endif %}

{% endblock %}

modules/yats/templates/tickets/new.html
{% extends "base.html" %}

{% load bootstrap_toolkit i18n %}

{% block title %}{% trans "new ticket" %}{% endblock %}

{% block extra_head %}
    {{ form.media }}
{% endblock %}

{% block content %}

    <h2>{% trans "new ticket" %}</h2>
    {% if mode == "simple" %}<p style="margin-top: -15px;"><small class="text-muted"><a href="/tickets/new/">{% trans "switch to extended form" %}</a></small></p>{% endif %}

    <p>&nbsp;</p>

    <form class="form-{{ layout }}" action="" method="post">
        {% csrf_token %}
        {{ form|as_bootstrap:layout }}
        {% if layout == "horizontal" %}
            <p class="form-actions">
                <input type="submit" value="{% trans "save" %}" class="btn btn-primary">
            </p>
        {% else %}
            <input type="submit" value="{% trans "save" %}" class="btn btn-primary">
        {% endif %}
    </form>

{% endblock %}

modules/yats/templates/tickets/querybuilder.html
{% extends "base.html" %}

{% load bootstrap_toolkit i18n %}

{% block title %}{% trans "search tickets" %}{% endblock %}

{% block extra_head %}
   {{ form.media }}
    <script src="//cdn.jsdelivr.net/npm/jquery-extendext@0.1.2/jQuery.extendext.min.js"></script>
    <link href="{{ STATIC_URL }}querybuilder/css/query-builder.default.css" type="text/css" rel="stylesheet" media="all">
    <script src="{{ STATIC_URL }}querybuilder/js/query-builder.standalone.js"></script>
    <script src="{{ STATIC_URL }}querybuilder/i18n/query-builder.{{ LANGUAGE_CODE }}.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <style>
      select {width: auto;}
      input {width: auto;}
    </style>
{% endblock %}

{% block content %}

    <h2>{% trans "search for tickets" %}</h2>
    <p style="margin-top: -15px;"><small class="text-muted"><a href="/tickets/search/simple/">{% trans "switch to simple search" %}</a></small></p>

    <p>&nbsp;</p>

    <div class="container">

    {{ form|as_querybuilder:request }}

      <p class="form-actions">
        <button class="btn btn-primary parse-json" id="btn-get">{% trans "search" %}</button>
        <button class="btn btn-warning reset" id="btn-reset">{% trans "reset" %}</button>
      </p>
    </div>

    <form method="post" name="data">
      <input type="hidden" id="query" name="query" />
    </form>

    <script>
      $('#btn-get').on('click', function() {
      var result = $('#builder').queryBuilder('getRules');

      if (!$.isEmptyObject(result)) {
        $('#query').val(JSON.stringify(result));
        document.data.submit();
      }
    });

    $('#btn-reset').on('click', function() {
      $('#builder').queryBuilder('reset');
    });
    </script>
{% endblock %}